name = "wingbox"
version = "0.1.0"
license = "license"
author = "Isaac Spencer"
maintainer = "22ispencer@gmail.com"
copyright = "Copyright 2024, Isaac Spencer"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
test = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

